export const FRASES = [
  { texto: 'Y anduvieron los hombres, hablaron los hombres... mas yo, el Señor, hablé.', referencia: 'Doctrina y Convenios 1:38' },
  { texto: 'Por tanto, id, y haced discípulos a todas las naciones, bautizándolos en el nombre del Padre, y del Hijo, y del Espíritu Santo.', referencia: 'Mateo 28:19' },
  { texto: 'Y si no tenéis fe, no tengáis esperanza; y si no tenéis esperanza, no podréis recibir la herencia que está preparada para vosotros.', referencia: 'Moroni 10:18' },
  { texto: 'Sígueme, y yo haré de vosotros pescadores de hombres.', referencia: 'Mateo 4:19' },
  { texto: 'Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.', referencia: 'Juan 3:16' },
  { texto: 'Y el que recibe la luz y persevera en Dios, recibe más luz; y esa luz crece más y más hasta el día perfecto.', referencia: 'Doctrina y Convenios 50:24' },
  { texto: 'Cantad al Señor un cántico nuevo; cantad al Señor, toda la tierra.', referencia: 'Salmos 96:1' },
  { texto: 'Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.', referencia: 'Mateo 6:33' },
  { texto: 'Y todo lo que pidiereis al Padre en mi nombre, que sea bueno y conveniente para mí, os será dado.', referencia: '3 Nefi 18:20' },
  { texto: 'El orgullo viene antes de la destrucción, y el espíritu altivo antes de la caída.', referencia: 'Proverbios 16:18' },
  { texto: 'Y cuando recibís una bendición de Dios, es porque se la agradecéis con el corazón.', referencia: 'Doctrina y Convenios 78:19' },
  { texto: 'Porque el Señor Dios siempre obra mediante convenios para bendecir a sus hijos.', referencia: 'Doctrina y Convenios 82:10' },
  { texto: 'Y nadie puede ayudar a esta obra a menos que sea humilde y lleno de amor.', referencia: 'Alma 5:28' },
  { texto: 'Yo soy la luz del mundo; el que me sigue, no andará en tinieblas, sino que tendrá la luz de la vida.', referencia: 'Juan 8:12' },
  { texto: 'Sed perfectos, como vuestro Padre que está en los cielos es perfecto.', referencia: 'Mateo 5:48' },
  { texto: 'Si Dios es por nosotros, ¿quién contra nosotros?', referencia: 'Romanos 8:31' },
  { texto: 'Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.', referencia: 'Filipenses 4:7' },
  { texto: 'El amor es sufrido, es benigno; el amor no tiene envidia, el amor no es jactancioso, no se envanece.', referencia: '1 Corintios 13:4' },
  { texto: 'No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo.', referencia: 'Isaías 41:10' },
  { texto: 'Haced lo bueno, no os canséis de hacer el bien, porque estáis poniendo los cimientos de una gran obra.', referencia: 'Doctrina y Convenios 64:33' },
  { texto: 'El Señor no mira lo que mira el hombre; pues el hombre mira lo que está delante de sus ojos, pero el Señor mira el corazón.', referencia: '1 Samuel 16:7' },
  { texto: 'Y sabemos que todas las cosas ayudan a bien para los que aman a Dios.', referencia: 'Romanos 8:28' },
  { texto: 'Vosotros sois la sal de la tierra... Vosotros sois la luz del mundo.', referencia: 'Mateo 5:13-14' },
  { texto: 'Con amor eterno te he amado; por tanto, te prolongué mi misericordia.', referencia: 'Jeremías 31:3' },
  { texto: 'Todo lo puedo en Cristo que me fortalece.', referencia: 'Filipenses 4:13' },
  { texto: 'Jehová es mi pastor; nada me faltará.', referencia: 'Salmos 23:1' },
  { texto: 'Clama a mí y yo te responderé, y te enseñaré cosas grandes y ocultas que tú no conoces.', referencia: 'Jeremías 33:3' },
  { texto: 'El principio de la sabiduría es el temor de Jehová.', referencia: 'Proverbios 9:10' },
  { texto: 'Andad en amor, como también Cristo nos amó y se entregó a sí mismo por nosotros.', referencia: 'Efesios 5:2' },
  { texto: 'El hombre bondadoso hace bien a su propia alma.', referencia: 'Proverbios 11:17' },
  { texto: 'Bienaventurados los pacificadores, porque ellos serán llamados hijos de Dios.', referencia: 'Mateo 5:9' },
  { texto: 'El que tiene mis mandamientos y los guarda, ese es el que me ama.', referencia: 'Juan 14:21' },
  { texto: 'Y ningún don espiritual se recibe a menos que se guarde la ley de Dios.', referencia: 'Doctrina y Convenios 88:33' },
  { texto: 'Sé fiel hasta la muerte, y yo te daré la corona de la vida.', referencia: 'Apocalipsis 2:10' },
  { texto: 'En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.', referencia: 'Juan 16:33' },
  { texto: 'El Señor fortalece a todos los que caen y levanta a todos los oprimidos.', referencia: 'Salmos 145:14' },
  { texto: 'Antes sed benignos unos con otros, misericordiosos, perdonándoos unos a otros.', referencia: 'Efesios 4:32' },
  { texto: 'Y si os recibe, entonces os hallaréis en mí, y yo en vosotros.', referencia: 'Éter 3:14' },
  { texto: 'El don de Dios es vida eterna en Cristo Jesús, Señor nuestro.', referencia: 'Romanos 6:23' },
  { texto: 'Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.', referencia: 'Mateo 11:28' },
  { texto: 'Tus testimonios son muy firmes; la santidad conviene a tu casa, oh Jehová, para siempre.', referencia: 'Salmos 93:5' },
  { texto: 'Y el que cree en mí será salvo, y será heredero del reino de los cielos.', referencia: 'Éter 4:18' },
  { texto: 'Sé fuerte y muy valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que vayas.', referencia: 'Josué 1:9' },
  { texto: 'Y todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres.', referencia: 'Colosenses 3:23' },
  { texto: 'El amor perfecto echa fuera todo temor.', referencia: '1 Juan 4:18' },
  { texto: 'Porque el Señor consuela a Sion; consuela a todos sus lugares destruidos.', referencia: 'Isaías 51:3' },
  { texto: 'No se turbe vuestro corazón; creéis en Dios, creed también en mí.', referencia: 'Juan 14:1' },
  { texto: 'Y el Espíritu mismo da testimonio a nuestro espíritu de que somos hijos de Dios.', referencia: 'Romanos 8:16' },
  { texto: 'El Señor es mi luz y mi salvación; ¿de quién temeré?', referencia: 'Salmos 27:1' },
  { texto: 'Amarás al Señor tu Dios con todo tu corazón, y con toda tu alma, y con toda tu mente.', referencia: 'Mateo 22:37' },
]

export function getFraseDelDia() {
  const hoy = new Date()
  const indice = (hoy.getFullYear() * 365 + hoy.getMonth() * 31 + hoy.getDate()) % FRASES.length
  return FRASES[indice]
}
